### ISSUE TITLE
Statikus analízis eszköz futtatása és jelzett hibák javítása - Codacy

### ISSUE THREAD

**Issue by omi9649** [omi9649/Omni-Notes#1]

**Comment by omi9649** [comment]
Codacy által felajánlott codesmells-ek javítása.

**Comment by banda13** [comment]
Pl: függvény nevében az _ karakter törlése.

**Comment by csabaiharosi** [comment]
A felfedett hibák közül csak keveset javítottunk ki, mert a rendelkezésre álló idő és információ nem volt elég mind a 314 hiba javítására

**Comment by micskeiz** [comment]
Ennél azért több hibát is meg lehetne nézni. Nem kell mindent javítani, de legalább annyit nézzetek meg és dokumentáljatok a wiki oldalra, hogy milyen jellegű problémákat jelzett a Codacity nagy vonalakban. Melyik hibák lehetnek a fontosak?
