### ISSUE TITLE
Manuális kód átvizsgálás elvégzése az alkalmazás egy részére

### ISSUE THREAD

**Issue by omi9649** [omi9649/Omni-Notes#3]

**Comment by omi9649** [comment]
Együtt átbeszéltük és megvizsgáltuk a hibákat/kódokat.

**Comment by banda13** [comment]
Mivel hatalmas kód miatt manuálisan nem lehet megtalálni az összes hibát, ezért a Codacy által ajánlottakbol indultunk ki.

**Comment by micskeiz** [comment]
Melyik részét vizsgáltátok át pontosan az alkalmazásnak? Ha nagy a kódbázis, akkor is ki lehet választani egy fontosabb osztályt, és sok mindent lehet átvizsgálni rajta anélkül is, hogy értenétek pontosan, hogy hogyan kapcsolódik az alkalmazás többi részéhez.
