### ISSUE TITLE
Egységtesztek készítése/kiegészítése

### ISSUE THREAD

**Issue by omi9649** [omi9649/Omni-Notes#4]

**Comment by banda13** [comment]
**GeocodeHelpeTest:** Teszt célja hogy adott földrajzi koordinátákhoz talál e létező helyet. Ha talál sikerült a teszt. BME I épület: 47.4727579, 19.0597071. Tesztelve, talált hozzá helyet! 
A teszt az új koordinátákkal frissítve.

**Comment by banda13** [comment]
ReminderHelperTest: 
- testGetRequestCode()
- testAddReminder()
- testRemoveReminder()
értesítése tesztelése

**Comment by banda13** [comment]
**SecurityTest:**
Egyszerű teszt enkódolása, dekódolásának a tesztelése, illetve egyből dekódolása a egyszerű szövegnek. Utóbbi teszt akkor sikeres, ha nem tudja dekódolni.

**Comment by omi9649** [comment]
A feladatot átvizsgáltam, véleményem szerint jó.

**Comment by csabaiharosi** [comment]
A módosított és kiegészített teszteket kipróbáltam, sikeresen lefutottak.

**Comment by banda13** [comment]
Új tesztek készítése: Node-ok tulajdonságait, Tag-ek beállítása, módosítása, törlése, illetve content-ben szereplő checkbox ([x] és []) lecserlése
