### ISSUE TITLE
Tesztek kódlefedettségének mérése _JaCoCo használatával

### ISSUE THREAD

**Issue by csabaiharosi** [omi9649/Omni-Notes#5]

**Comment by banda13** [comment]
Netes tutoriál alapján sikerült beüzemelni a rendszert, amely 1 hibával futott le sikeresen. (92%-ban)

**Comment by omi9649** [comment]
Nem tudtunk rájönni a hiba forrására.

**Comment by csabaiharosi** [comment]
A build.gradle-ben hozzáadtuk a pluginekhez a jacoco-t
