### ISSUE TITLE
Automatizált UI tesztek készítése Esspresso-val

### ISSUE THREAD

**Issue by csabaiharosi** [omi9649/Omni-Notes#6]

**Comment by csabaiharosi** [comment]
Az Android Testing Support Library-nek a Record Espresso test feature-ét felhasználva létrehoztunk kettő UI tesztet, melyek sikeresen lefutottak.

**Comment by omi9649** [comment]
Az elkészítettet teszteket felülvizsgáltam, megfelelően működött.

**Comment by banda13** [comment]
A tesztek note illetve checklist létrehozásának, illetve alert beállításának lépéseit fedik le, helyesen működnek!
